<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use http\Exception\InvalidArgumentException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastArticle($page = 1, $max = 10 ){

        $queryBuilder = $this->createQueryBuilder('a')
            ->orderBy("a.publishedDate","DESC");
        $query = $queryBuilder->getQuery();

        //return $query->getResult();
        return $this->getPaginator($query, $page, $max);
    }

    public function getArticleOfSerie($id, $page = 1, $max = 10){

        $queryBuilder = $this->createQueryBuilder('a')
            ->where('a.serie = ?1')
            ->orderBy("a.publishedDate","DESC")
            ->setParameter(1,$id);


        $query = $queryBuilder->getQuery();

        return $this->getPaginator($query, $page, $max);

    }

    public static function getPaginator($query, $page, $max){
        if (!is_numeric($page)) {
            throw new InvalidArgumentException(
                'value of argument $page is incorrect (value : ' . $page . ').'
            );
        }

        if ($page < 1) {
            throw new NotFoundHttpException('Asked page does not exist');
        }

        if (!is_numeric($max)) {
            throw new InvalidArgumentException(
                'Value of $nbMaxParPage is incorrect (value : ' . $max . ').'
            );
        }

        $firstResult = ($page - 1) * $max;
        $query->setFirstResult($firstResult)->setMaxResults($max);
        $paginator = new Paginator($query);

        if ( ($paginator->count() <= $firstResult) && $page != 1) {
            throw new NotFoundHttpException('Asked page does not exist'); // page 404, sauf pour la première page
        }

        return $paginator;

    }

}
