<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastArticle(int $max){
        $em = $this->getEntityManager();

        $queryBuilder = $this->createQueryBuilder('a')
            ->setMaxResults($max)
            ->orderBy("a.publishedDate");
        $query = $queryBuilder->getQuery();
        return $query->getResult();
    }

}
