<?php

namespace AppBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSameAs($text){

        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT s.name FROM serie s
                WHERE s.name LIKE :text';


        $stmt = $conn->prepare($sql);
        $stmt->execute(array(':text' => $text . '%'));

        return $stmt->fetchAll();
    }
}
